export enum QuestionType {
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    FILL_IN = "FILL_IN",
    MULTIPLE_CHOICE_IMAGE = "MULTIPLE_CHOICE_IMAGE",
    FILL_IN_IMAGE = "FILL_IN_IMAGE",
}

export enum Section {
    MATH = "MATH",
    ENGLISH = "ENGLISH",
}

export enum SubSection {
    REVISING_EDITING = "REVISING_EDITING",
    READING_COMPREHENSION = "READING_COMPREHENSION",
    MATH_FILL_IN = "MATH_FILL_IN",
    MATH_MULTIPLE_CHOICE = "MATH_MULTIPLE_CHOICE",
}